(function () {
  const devices = [
    {
      id: "odin3-base",
      name: "Odin 3 Base",
      family: "Odin 3",
      ram: 8,
      storage: 128,
      performanceTier: "enthusiast",
      computeRank: 4,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 3,
      priceUsd: 399,
      available: true,
      recommendable: true
    },
    {
      id: "odin3-pro",
      name: "Odin 3 Pro",
      family: "Odin 3",
      ram: 12,
      storage: 256,
      performanceTier: "enthusiast",
      computeRank: 4,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 4,
      priceUsd: 499,
      available: true,
      recommendable: true
    },
    {
      id: "odin3-max",
      name: "Odin 3 Max",
      family: "Odin 3",
      ram: 16,
      storage: 512,
      performanceTier: "enthusiast",
      computeRank: 4,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 5,
      priceUsd: 599,
      available: true,
      recommendable: true
    },
    {
      id: "odin3-ultra",
      name: "Odin 3 Ultra",
      family: "Odin 3",
      ram: 24,
      storage: 1024,
      performanceTier: "enthusiast",
      computeRank: 4,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 6,
      priceUsd: 699,
      available: true,
      recommendable: true
    },
    {
      id: "thor-lite",
      name: "Thor Lite",
      family: "Thor",
      ram: 8,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      formFactor: "clamshell",
      dualScreen: true,
      positioning: "dual-screen",
      priceIndex: 2,
      priceUsd: 299,
      available: true,
      recommendable: true
    },
    {
      id: "thor-base",
      name: "Thor Base",
      family: "Thor",
      ram: 8,
      storage: 128,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "clamshell",
      dualScreen: true,
      positioning: "dual-screen",
      priceIndex: 3,
      priceUsd: 399,
      available: true,
      recommendable: true
    },
    {
      id: "thor-pro",
      name: "Thor Pro",
      family: "Thor",
      ram: 12,
      storage: 256,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "clamshell",
      dualScreen: true,
      positioning: "dual-screen",
      priceIndex: 4,
      priceUsd: 499,
      available: true,
      recommendable: true
    },
    {
      id: "thor-max",
      name: "Thor Max",
      family: "Thor",
      ram: 16,
      storage: 1024,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "clamshell",
      dualScreen: true,
      positioning: "dual-screen",
      priceIndex: 5,
      priceUsd: 599,
      available: true,
      recommendable: true
    },
    {
      id: "odin2-portal-base",
      name: "Odin2 Portal Base",
      family: "Odin2 Portal",
      ram: 8,
      storage: 128,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 299,
      available: true,
      recommendable: true
    },
    {
      id: "odin2-portal-pro",
      name: "Odin2 Portal Pro",
      family: "Odin2 Portal",
      ram: 12,
      storage: 256,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 3,
      priceUsd: 399,
      available: true,
      recommendable: true
    },
    {
      id: "odin2-portal-max",
      name: "Odin2 Portal Max",
      family: "Odin2 Portal",
      ram: 16,
      storage: 512,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 4,
      priceUsd: 499,
      available: true,
      recommendable: true
    },
    {
      id: "odin-lite",
      name: "Odin Lite",
      family: "Odin",
      ram: 4,
      storage: 64,
      performanceTier: "mid",
      computeRank: 2,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 1,
      priceUsd: 199,
      available: false,
      recommendable: false
    },
    {
      id: "odin-base",
      name: "Odin Base",
      family: "Odin",
      ram: 4,
      storage: 64,
      performanceTier: "mid",
      computeRank: 2,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 1,
      priceUsd: 199,
      available: false,
      recommendable: false
    },
    {
      id: "odin-pro",
      name: "Odin Pro",
      family: "Odin",
      ram: 8,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 2,
      priceUsd: 299,
      available: false,
      recommendable: false
    },
    {
      id: "odin2-base",
      name: "Odin 2 Base",
      family: "Odin 2",
      ram: 8,
      storage: 128,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 2,
      priceUsd: 299,
      available: false,
      recommendable: false
    },
    {
      id: "odin2-pro",
      name: "Odin 2 Pro",
      family: "Odin 2",
      ram: 12,
      storage: 256,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 3,
      priceUsd: 399,
      available: false,
      recommendable: false
    },
    {
      id: "odin2-max",
      name: "Odin 2 Max",
      family: "Odin 2",
      ram: 16,
      storage: 512,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 4,
      priceUsd: 499,
      available: false,
      recommendable: false
    },
    {
      id: "loki",
      name: "Loki",
      family: "Loki",
      ram: 16,
      storage: 512,
      performanceTier: "enthusiast",
      computeRank: 4,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 4,
      priceUsd: 499,
      available: false,
      recommendable: false
    }
  ];

  window.DevicesData = devices;
})();
