(function () {
  const devices = [
    {
      id: "odin3-base",
      brand: "ayn",
      name: "Odin 3 Base",
      family: "Odin 3",
      ram: 8,
      storage: 128,
      performanceTier: "enthusiast",
      computeRank: 4,
      useCaseLane: "high-end-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 3,
      priceUsd: 339,
      storageSpec: "UFS 3.1",
      priorStorageSpec: "UFS 4.0",
      currentBatchLabel: "Batch 7 pre-order",
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "odin3-pro",
      brand: "ayn",
      name: "Odin 3 Pro",
      family: "Odin 3",
      ram: 12,
      storage: 256,
      performanceTier: "enthusiast",
      computeRank: 4,
      useCaseLane: "high-end-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 4,
      priceUsd: 439,
      storageSpec: "UFS 3.1",
      priorStorageSpec: "UFS 4.0",
      currentBatchLabel: "Batch 7 pre-order",
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "odin3-max",
      brand: "ayn",
      name: "Odin 3 Max",
      family: "Odin 3",
      ram: 16,
      storage: 512,
      performanceTier: "enthusiast",
      computeRank: 4,
      useCaseLane: "high-end-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 5,
      priceUsd: 489,
      storageSpec: "UFS 3.1",
      priorStorageSpec: "UFS 4.0",
      currentBatchLabel: "Batch 7 pre-order",
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "odin3-ultra",
      brand: "ayn",
      name: "Odin 3 Ultra",
      family: "Odin 3",
      ram: 24,
      storage: 1024,
      performanceTier: "enthusiast",
      computeRank: 4,
      useCaseLane: "high-end-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 6,
      priceUsd: 519,
      storageSpec: "UFS 3.1",
      priorStorageSpec: "UFS 4.0",
      currentBatchLabel: "Batch 7 pre-order",
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "thor-lite",
      brand: "ayn",
      name: "Thor Lite",
      family: "Thor",
      ram: 8,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "clamshell",
      formFactor: "clamshell",
      dualScreen: true,
      positioning: "dual-screen",
      priceIndex: 2,
      priceUsd: 249,
      storageSpec: "UFS 3.1",
      priorStorageSpec: "UFS 4.0",
      currentBatchLabel: "Batch 6 pre-order",
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "thor-base",
      brand: "ayn",
      name: "Thor Base",
      family: "Thor",
      ram: 8,
      storage: 128,
      performanceTier: "high",
      computeRank: 3,
      useCaseLane: "clamshell",
      formFactor: "clamshell",
      dualScreen: true,
      positioning: "dual-screen",
      priceIndex: 3,
      priceUsd: 319,
      storageSpec: "UFS 3.1",
      priorStorageSpec: "UFS 4.0",
      currentBatchLabel: "Batch 6 pre-order",
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "thor-pro",
      brand: "ayn",
      name: "Thor Pro",
      family: "Thor",
      ram: 12,
      storage: 256,
      performanceTier: "high",
      computeRank: 3,
      useCaseLane: "clamshell",
      formFactor: "clamshell",
      dualScreen: true,
      positioning: "dual-screen",
      priceIndex: 4,
      priceUsd: 399,
      storageSpec: "UFS 3.1",
      priorStorageSpec: "UFS 4.0",
      currentBatchLabel: "Batch 6 pre-order",
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "thor-max",
      brand: "ayn",
      name: "Thor Max",
      family: "Thor",
      ram: 16,
      storage: 1024,
      performanceTier: "high",
      computeRank: 3,
      useCaseLane: "clamshell",
      formFactor: "clamshell",
      dualScreen: true,
      positioning: "dual-screen",
      priceIndex: 5,
      priceUsd: 549,
      storageSpec: "UFS 3.1",
      priorStorageSpec: "UFS 4.0",
      currentBatchLabel: "Batch 6 pre-order",
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "odin2-portal-base",
      brand: "ayn",
      name: "Odin2 Portal Base",
      family: "Odin2 Portal",
      ram: 8,
      storage: 128,
      performanceTier: "high",
      computeRank: 3,
      useCaseLane: "balanced-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 249,
      available: true,
      recommendable: true
    },
    {
      id: "odin2-portal-pro",
      brand: "ayn",
      name: "Odin2 Portal Pro",
      family: "Odin2 Portal",
      ram: 12,
      storage: 256,
      performanceTier: "high",
      computeRank: 3,
      useCaseLane: "balanced-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 4,
      priceUsd: 369,
      available: true,
      recommendable: true
    },
    {
      id: "odin2-portal-max",
      brand: "ayn",
      name: "Odin2 Portal Max",
      family: "Odin2 Portal",
      ram: 16,
      storage: 512,
      performanceTier: "high",
      computeRank: 3,
      useCaseLane: "balanced-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 5,
      priceUsd: 449,
      available: true,
      recommendable: true
    },
    {
      id: "retroid-pocket-g2",
      brand: "retroid",
      name: "Pocket G2",
      family: "Pocket G2",
      ram: 8,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 219,
      available: true,
      recommendable: true
    },
    {
      id: "retroid-pocket-5",
      brand: "retroid",
      name: "Pocket 5",
      family: "Pocket 5",
      ram: 8,
      storage: 128,
      performanceTier: "high",
      computeRank: 3,
      useCaseLane: "balanced-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 199,
      available: true,
      recommendable: true
    },
    {
      id: "retroid-pocket-flip-2",
      brand: "retroid",
      name: "Pocket Flip 2",
      family: "Pocket Flip 2",
      ram: 8,
      storage: 128,
      performanceTier: "high",
      computeRank: 3,
      useCaseLane: "clamshell",
      formFactor: "clamshell",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 209,
      available: true,
      recommendable: true
    },
    {
      id: "retroid-pocket-6",
      brand: "retroid",
      name: "Pocket 6 (pre-order)",
      family: "Pocket 6",
      ram: 8,
      storage: 128,
      performanceTier: "enthusiast",
      computeRank: 4,
      useCaseLane: "high-end-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 2,
      priceUsd: 244,
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "retroid-pocket-6-12gb",
      brand: "retroid",
      name: "Pocket 6 12GB/256GB (pre-order)",
      family: "Pocket 6",
      ram: 12,
      storage: 256,
      performanceTier: "enthusiast",
      computeRank: 4,
      useCaseLane: "high-end-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 3,
      priceUsd: 279,
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "retroid-pocket-mini-v2",
      brand: "retroid",
      name: "Pocket Mini V2",
      family: "Pocket Mini V2",
      ram: 6,
      storage: 128,
      performanceTier: "mid",
      computeRank: 3,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 1,
      priceUsd: 189,
      available: true,
      recommendable: false
    },
    {
      id: "retroid-pocket-classic",
      brand: "retroid",
      name: "Pocket Classic",
      family: "Pocket Classic",
      ram: 6,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "vertical",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 149,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-cube",
      brand: "anbernic",
      name: "RG Cube",
      family: "RG Cube",
      ram: 8,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 141.78,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg406h",
      brand: "anbernic",
      name: "RG406H",
      family: "RG406H",
      ram: 8,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 149.99,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg406v",
      brand: "anbernic",
      name: "RG406V",
      family: "RG406V",
      ram: 8,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "vertical",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 164.99,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg-slide",
      brand: "anbernic",
      name: "RG Slide",
      family: "RG Slide",
      ram: 8,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 155.68,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg556",
      brand: "anbernic",
      name: "RG556",
      family: "RG556",
      ram: 8,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 180.39,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg557",
      brand: "anbernic",
      name: "RG557",
      family: "RG557",
      ram: 12,
      storage: 256,
      performanceTier: "high",
      computeRank: 3,
      useCaseLane: "balanced-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 3,
      priceUsd: 274.02,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg34xx",
      brand: "anbernic",
      name: "RG34XX",
      family: "RG34XX",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 59.99,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg35xx-plus",
      brand: "anbernic",
      name: "RG35XX Plus",
      family: "RG35XX Plus",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "vertical",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 49.99,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg35xx-h",
      brand: "anbernic",
      name: "RG35XX H",
      family: "RG35XX",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 57.99,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg35xx-sp",
      brand: "anbernic",
      name: "RG35XX SP",
      family: "RG35XX SP",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "clamshell",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 57.99,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg34xxsp",
      brand: "anbernic",
      name: "RG34XXSP",
      family: "RG34XXSP",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "clamshell",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 67.99,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg40xx-h",
      brand: "anbernic",
      name: "RG40XX H",
      family: "RG40XX",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 67.99,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-rg40xx-v",
      brand: "anbernic",
      name: "RG40XX V",
      family: "RG40XX",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "vertical",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 67.99,
      available: true,
      recommendable: true
    },
    {
      id: "anbernic-cube-xx",
      brand: "anbernic",
      name: "CubeXX",
      family: "CubeXX",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 61.91,
      available: true,
      recommendable: true
    },
    {
      id: "powkiddy-rgb10x",
      brand: "powkiddy",
      name: "RGB10X",
      family: "RGB10X",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 39.99,
      available: true,
      recommendable: true
    },
    {
      id: "powkiddy-v10",
      brand: "powkiddy",
      name: "V10",
      family: "V10",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 39.99,
      available: true,
      recommendable: true
    },
    {
      id: "powkiddy-v90s",
      brand: "powkiddy",
      name: "V90S",
      family: "V90S",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "clamshell",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 44.99,
      available: true,
      recommendable: true
    },
    {
      id: "powkiddy-v20",
      brand: "powkiddy",
      name: "V20",
      family: "V20",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 49.99,
      available: true,
      recommendable: true
    },
    {
      id: "powkiddy-rgb20s",
      brand: "powkiddy",
      name: "RGB20S",
      family: "RGB20S",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 49.99,
      available: true,
      recommendable: true
    },
    {
      id: "powkiddy-x35h",
      brand: "powkiddy",
      name: "X35H",
      family: "X35H",
      ram: 1,
      storage: 64,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 59.99,
      available: true,
      recommendable: true
    },
    {
      id: "powkiddy-rgb20-pro",
      brand: "powkiddy",
      name: "RGB20 Pro",
      family: "RGB20 Pro",
      ram: 1,
      storage: 64,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 69.99,
      available: true,
      recommendable: true
    },
    {
      id: "powkiddy-rgb20sx",
      brand: "powkiddy",
      name: "RGB20SX",
      family: "RGB20SX",
      ram: 1,
      storage: 64,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "vertical",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 69.99,
      available: true,
      recommendable: true
    },
    {
      id: "powkiddy-rgb30",
      brand: "powkiddy",
      name: "RGB30",
      family: "RGB30",
      ram: 1,
      storage: 64,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 69.99,
      available: true,
      recommendable: true
    },
    {
      id: "powkiddy-x55",
      brand: "powkiddy",
      name: "X55",
      family: "X55",
      ram: 2,
      storage: 64,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 79.99,
      available: true,
      recommendable: true
    },
    {
      id: "miyoo-a30",
      brand: "miyoo",
      name: "A30",
      family: "A30",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 1,
      priceUsd: 49.99,
      available: true,
      recommendable: true
    },
    {
      id: "miyoo-mini-v4",
      brand: "miyoo",
      name: "Mini V4",
      family: "Mini V4",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "vertical",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 59.99,
      available: true,
      recommendable: true
    },
    {
      id: "miyoo-mini-plus",
      brand: "miyoo",
      name: "Mini Plus",
      family: "Mini Plus",
      ram: 1,
      storage: 64,
      performanceTier: "light",
      computeRank: 1,
      useCaseLane: "retro-focused",
      formFactor: "vertical",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 69.99,
      available: true,
      recommendable: true
    },
    {
      id: "miyoo-flip",
      brand: "miyoo",
      name: "Flip",
      family: "Flip",
      ram: 1,
      storage: 64,
      performanceTier: "mid",
      computeRank: 2,
      useCaseLane: "retro-focused",
      formFactor: "clamshell",
      dualScreen: false,
      positioning: "balanced",
      priceIndex: 2,
      priceUsd: 119.9,
      available: true,
      recommendable: true
    },
    {
      id: "ayaneo-pocket-ace",
      brand: "ayaneo",
      name: "Pocket ACE",
      family: "Pocket ACE",
      ram: 8,
      storage: 128,
      performanceTier: "enthusiast",
      computeRank: 4,
      useCaseLane: "high-end-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 4,
      priceUsd: 459,
      available: true,
      recommendable: true
    },
    {
      id: "ayaneo-pocket-s2",
      brand: "ayaneo",
      name: "Pocket S2 (pre-order)",
      family: "Pocket S2",
      ram: 8,
      storage: 128,
      performanceTier: "enthusiast",
      computeRank: 4,
      useCaseLane: "high-end-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 4,
      priceUsd: 439,
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "ayaneo-pocket-evo",
      brand: "ayaneo",
      name: "Pocket EVO",
      family: "Pocket EVO",
      ram: 8,
      storage: 128,
      performanceTier: "enthusiast",
      computeRank: 4,
      useCaseLane: "high-end-android",
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "premium",
      priceIndex: 5,
      priceUsd: 599,
      available: true,
      recommendable: true
    },
    {
      id: "ayaneo-pocket-ds",
      brand: "ayaneo",
      name: "Pocket DS (pre-order)",
      family: "Pocket DS",
      ram: 8,
      storage: 128,
      performanceTier: "enthusiast",
      computeRank: 4,
      useCaseLane: "clamshell",
      formFactor: "clamshell",
      dualScreen: true,
      positioning: "dual-screen",
      priceIndex: 6,
      priceUsd: 559,
      available: true,
      recommendable: true,
      preOrder: true
    },
    {
      id: "razer-edge",
      brand: "razer",
      name: "Razer Edge",
      family: "Razer Edge",
      ram: 6,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 3,
      priceUsd: 249.99,
      available: true,
      recommendable: false
    },
    {
      id: "odin-lite",
      brand: "ayn",
      name: "Odin Lite",
      family: "Odin",
      ram: 4,
      storage: 64,
      performanceTier: "mid",
      computeRank: 2,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 1,
      priceUsd: 199,
      available: false,
      recommendable: false
    },
    {
      id: "odin-base",
      brand: "ayn",
      name: "Odin Base",
      family: "Odin",
      ram: 4,
      storage: 64,
      performanceTier: "mid",
      computeRank: 2,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 1,
      priceUsd: 199,
      available: false,
      recommendable: false
    },
    {
      id: "odin-pro",
      brand: "ayn",
      name: "Odin Pro",
      family: "Odin",
      ram: 8,
      storage: 128,
      performanceTier: "mid",
      computeRank: 2,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 2,
      priceUsd: 299,
      available: false,
      recommendable: false
    },
    {
      id: "odin2-base",
      brand: "ayn",
      name: "Odin 2 Base",
      family: "Odin 2",
      ram: 8,
      storage: 128,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 2,
      priceUsd: 299,
      available: false,
      recommendable: false
    },
    {
      id: "odin2-pro",
      brand: "ayn",
      name: "Odin 2 Pro",
      family: "Odin 2",
      ram: 12,
      storage: 256,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 3,
      priceUsd: 399,
      available: false,
      recommendable: false
    },
    {
      id: "odin2-max",
      brand: "ayn",
      name: "Odin 2 Max",
      family: "Odin 2",
      ram: 16,
      storage: 512,
      performanceTier: "high",
      computeRank: 3,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 4,
      priceUsd: 499,
      available: false,
      recommendable: false
    },
    {
      id: "loki",
      brand: "ayn",
      name: "Loki",
      family: "Loki",
      ram: 16,
      storage: 512,
      performanceTier: "enthusiast",
      computeRank: 4,
      formFactor: "horizontal",
      dualScreen: false,
      positioning: "legacy",
      priceIndex: 4,
      priceUsd: 499,
      available: false,
      recommendable: false
    }
  ];

  window.DevicesData = devices;
})();
